services:
  pytorch_v1:
      shm_size: "10gb"
      build:
        context: ./docker/pytorch_es
        args:
          - http_proxy
          - https_proxy
          - HTTP_PROXY
          - HTTPS_PROXY
      tty: true
      ports:
        - "10170:8888"
      environment:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
        - PYTHONPATH=/workspace/python
      volumes:
        - ./data:/workspace/data:cached
        - ./python:/workspace/python:cached
      command:
        jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
